


export const HomeScreenData = [
    {
        "id": 3731564,
        "title": "The Girl and the Bear",
        "description": "<p>Illustration practice :)\n<br />All photoshop on this one.\n<br />More stuff over at my instagram: <a href=\"https://www.instagram.com/mklgustafsson/\" rel=\"noreferrer\">https://www.instagram.com/mklgustafsson/</a></p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/5031/screenshots/3731564/mikael_gustafsson_dribbble.png",
            "normal": "https://cdn.dribbble.com/users/5031/screenshots/3731564/mikael_gustafsson_dribbble_1x.png",
            "teaser": "https://cdn.dribbble.com/users/5031/screenshots/3731564/mikael_gustafsson_dribbble_teaser.png"
        },
        "views_count": 11642,
        "likes_count": 1610,
        "comments_count": 49,
        "attachments_count": 0,
        "rebounds_count": 0,
        "buckets_count": 100,
        "created_at": "2017-08-13T10:55:45Z",
        "updated_at": "2017-08-13T11:00:14Z",
        "html_url": "https://dribbble.com/shots/3731564-The-Girl-and-the-Bear",
        "attachments_url": "https://api.dribbble.com/v1/shots/3731564/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3731564/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3731564/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3731564/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3731564/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3731564/rebounds",
        "animated": false,
        "tags": [
            "bear",
            "concept art",
            "environment",
            "forest",
            "girl",
            "illustration",
            "snow"
        ],
        "user": {
            "id": 5031,
            "name": "Mikael Gustafsson",
            "username": "MikaelGustafsson",
            "html_url": "https://dribbble.com/MikaelGustafsson",
            "avatar_url": "https://cdn.dribbble.com/users/5031/avatars/normal/d3943f9b82be61fbcd9b3bac6a635d67.jpg?1498036140",
            "bio": "<a href=\"https://twitter.com/MklGustafsson\" rel=\"nofollow noreferrer\">twitter.com/MklGustafsson</a>     <a href=\"https://instagram.com/mklgustafsson/\" rel=\"nofollow noreferrer\">instagram.com/mklgustafsson</a>",
            "location": "Stockholm, Sweden",
            "links": {
                "web": "https://instagram.com/mklgustafsson/",
                "twitter": "https://twitter.com/mklgustafsson"
            },
            "buckets_count": 0,
            "comments_received_count": 1220,
            "followers_count": 17846,
            "followings_count": 234,
            "likes_count": 184,
            "likes_received_count": 41318,
            "projects_count": 0,
            "rebounds_received_count": 4,
            "shots_count": 35,
            "teams_count": 0,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/5031/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/5031/followers",
            "following_url": "https://api.dribbble.com/v1/users/5031/following",
            "likes_url": "https://api.dribbble.com/v1/users/5031/likes",
            "projects_url": "https://api.dribbble.com/v1/users/5031/projects",
            "shots_url": "https://api.dribbble.com/v1/users/5031/shots",
            "teams_url": "https://api.dribbble.com/v1/users/5031/teams",
            "created_at": "2010-10-09T10:47:50Z",
            "updated_at": "2017-08-20T14:00:10Z"
        },
        "team": null
    },
    {
        "id": 3717873,
        "title": "Introducing DesignBetter.Co by InVision",
        "description": "<p>Today we’re thrilled to launch <a href=\"https://www.designbetter.co/\" rel=\"nofollow noreferrer\">DesignBetter.Co</a>—the essential guide to product design and an incredible effort from our Design Education team.</p>\n\n<p>Product design is hard. Mastering it requires a lot of skills, from sketching to design thinking to growing your leadership abilities. </p>\n\n<p>We interviewed dozens of the world’s leading designers at companies like Google, Airbnb, Netflix, Facebook, Slack, and more, to create the definitive guide to elevating your design practice. </p>\n\n<p>Read the books Principles of Product Design, The Design Thinking Handbook, and The Design Leadership Handbook—or dive into our DesignBetter.Co Podcast, featuring David Kelley, Irene Au, and more.</p>\n\n<p>Can’t wait to hear your feedback (and hit “L” if you’re loving our design team’s amazing work on this project!). </p>\n\n<p><a href=\"https://www.designbetter.co/\" rel=\"nofollow noreferrer\">Explore DesignBetter.Co now</a></p>\n\n<p><a href=\"https://dribbble.com/4988\">@aaron stump</a>: Creative &amp; Art Direction\n<br /><a href=\"https://dribbble.com/4931\">@Jared Granger</a> : Brand Design &amp; Art Direction\n<br /><a href=\"https://dribbble.com/62319\">@Anton Aheichanka</a>: Web Design &amp; Animation\n<br /><a href=\"https://dribbble.com/376684\">@Luisa Mancera</a>: Web Design\n<br /><a href=\"https://dribbble.com/246575\">@Connor Murphy</a>: Design\n<br /><a href=\"https://dribbble.com/77628\">@Jack Daly</a>: Illustration\n</p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/4931/screenshots/3717873/designbetter-dribbble-announcement.gif",
            "normal": "https://cdn.dribbble.com/users/4931/screenshots/3717873/designbetter-dribbble-announcement_1x.gif",
            "teaser": "https://cdn.dribbble.com/users/4931/screenshots/3717873/designbetter-dribbble-announcement_teaser.gif"
        },
        "views_count": 15737,
        "likes_count": 1386,
        "comments_count": 51,
        "attachments_count": 0,
        "rebounds_count": 1,
        "buckets_count": 132,
        "created_at": "2017-08-07T18:45:57Z",
        "updated_at": "2017-08-08T11:43:05Z",
        "html_url": "https://dribbble.com/shots/3717873-Introducing-DesignBetter-Co-by-InVision",
        "attachments_url": "https://api.dribbble.com/v1/shots/3717873/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3717873/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3717873/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3717873/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3717873/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3717873/rebounds",
        "animated": true,
        "tags": [
            "animation",
            "book",
            "brand",
            "design",
            "design thinking",
            "education",
            "homepage",
            "layout",
            "leadership",
            "podcast",
            "product design",
            "ui"
        ],
        "user": {
            "id": 4931,
            "name": "Jared Granger",
            "username": "jaredgranger",
            "html_url": "https://dribbble.com/jaredgranger",
            "avatar_url": "https://cdn.dribbble.com/users/4931/avatars/normal/ff8090b92d7cd3164aba232376ff1f29.png?1432644230",
            "bio": "Designer <a href=\"https://dribbble.com/InVisionApp\">@InVisionApp</a>. ",
            "location": "Pensacola, FL",
            "links": {
                "web": "http://jaredgranger.com",
                "twitter": "https://twitter.com/jaredpgranger"
            },
            "buckets_count": 0,
            "comments_received_count": 1105,
            "followers_count": 3377,
            "followings_count": 597,
            "likes_count": 13066,
            "likes_received_count": 16051,
            "projects_count": 0,
            "rebounds_received_count": 39,
            "shots_count": 190,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/4931/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/4931/followers",
            "following_url": "https://api.dribbble.com/v1/users/4931/following",
            "likes_url": "https://api.dribbble.com/v1/users/4931/likes",
            "projects_url": "https://api.dribbble.com/v1/users/4931/projects",
            "shots_url": "https://api.dribbble.com/v1/users/4931/shots",
            "teams_url": "https://api.dribbble.com/v1/users/4931/teams",
            "created_at": "2010-10-05T18:13:53Z",
            "updated_at": "2017-08-20T11:24:26Z"
        },
        "team": {
            "id": 50942,
            "name": "InVision",
            "username": "InVisionApp",
            "html_url": "https://dribbble.com/InVisionApp",
            "avatar_url": "https://cdn.dribbble.com/users/50942/avatars/normal/bb4685dbe9de3d043ccef3293247a579.png?1493296205",
            "bio": "Design better experiences with InVision, a prototyping, collaboration, and workflow platform.",
            "location": "New York, NY",
            "links": {
                "web": "http://www.InVisionApp.com",
                "twitter": "https://twitter.com/InVisionApp"
            },
            "buckets_count": 0,
            "comments_received_count": 353,
            "followers_count": 31650,
            "followings_count": 1011,
            "likes_count": 270,
            "likes_received_count": 1127,
            "projects_count": 2,
            "rebounds_received_count": 19,
            "shots_count": 200,
            "can_upload_shot": true,
            "type": "Team",
            "pro": false,
            "buckets_url": "https://api.dribbble.com/v1/users/50942/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/50942/followers",
            "following_url": "https://api.dribbble.com/v1/users/50942/following",
            "likes_url": "https://api.dribbble.com/v1/users/50942/likes",
            "projects_url": "https://api.dribbble.com/v1/users/50942/projects",
            "shots_url": "https://api.dribbble.com/v1/users/50942/shots",
            "created_at": "2011-08-05T20:04:14Z",
            "updated_at": "2017-08-20T11:38:46Z",
            "members_count": 25,
            "members_url": "https://api.dribbble.com/v1/teams/50942/members",
            "team_shots_url": "https://api.dribbble.com/v1/teams/50942/shots"
        }
    },
    {
        "id": 3735577,
        "title": "Designing the DesignBetter.Co books",
        "description": "<p>Each book in the DesignBetter.Co library features a mix of deep insights and quick learnings. When we concepted each book, we knew we wanted stunning, distinctive illustrations to capture that interplay between immersive depth and sparks of delight in the words. </p>\n\n<p>For instance, in <a href=\"https://www.designbetter.co/principles-of-product-design\" rel=\"nofollow noreferrer\">Principles of Product Design</a>, you can go on an exploration of everything from how to conduct surveys to how to structure design reviews—or just listen to a quick clip of a design leader interview or try out a fast team exercise. </p>\n\n<p>Illustrations needed to set the mood for deep, impactful learning while staying playful true to the DesignBetter.Co brand.</p>\n\n<p>Enter <a href=\"https://dribbble.com/jack-daly\" rel=\"nofollow noreferrer\">Jack Daly</a>, the creator of the out-of-this-world illustrations bringing the DesignBetter.Co books to life. It was amazing to work with Jack and the rest of the team to incorporate rich illustration into each book, and to make sure every element worked harmoniously together.</p>\n\n<p>Hit “L” to give Jack and the rest of the team some love, and check out <a href=\"https://www.designbetter.co/\" rel=\"nofollow noreferrer\">DesignBetter.Co</a> to see more of our work!</p>\n\n<p><a href=\"https://dribbble.com/aaronstump\" rel=\"nofollow noreferrer\">Aaron Stump</a>: Creative &amp; Art Direction\n<br /><a href=\"https://dribbble.com/jaredgranger\" rel=\"nofollow noreferrer\">Jared Granger</a>: Brand Design &amp; Art Direction\n<br /><a href=\"https://dribbble.com/madebyanton\" rel=\"nofollow noreferrer\">Anton Aheichanka</a>: Web Design &amp; Animation\n<br /><a href=\"https://dribbble.com/luisamf\" rel=\"nofollow noreferrer\">Luisa Mancera</a>: Web Design\n<br /><a href=\"https://dribbble.com/connormurphy\" rel=\"nofollow noreferrer\">Connor Murphy</a>: Design\n<br /><a href=\"https://dribbble.com/jack-daly\" rel=\"nofollow noreferrer\">Jack Daly</a>: Illustration</p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/62319/screenshots/3735577/designbetter-dribbble-announcement-2.gif",
            "normal": "https://cdn.dribbble.com/users/62319/screenshots/3735577/designbetter-dribbble-announcement-2_1x.gif",
            "teaser": "https://cdn.dribbble.com/users/62319/screenshots/3735577/designbetter-dribbble-announcement-2_teaser.gif"
        },
        "views_count": 13968,
        "likes_count": 1106,
        "comments_count": 24,
        "attachments_count": 1,
        "rebounds_count": 0,
        "buckets_count": 103,
        "created_at": "2017-08-15T03:56:32Z",
        "updated_at": "2017-08-15T11:00:02Z",
        "html_url": "https://dribbble.com/shots/3735577-Designing-the-DesignBetter-Co-books",
        "attachments_url": "https://api.dribbble.com/v1/shots/3735577/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3735577/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3735577/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3735577/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3735577/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3735577/rebounds",
        "animated": true,
        "tags": [
            "animation",
            "book",
            "brand",
            "design",
            "education",
            "illustration",
            "invision",
            "landing",
            "layout",
            "page",
            "prototyping",
            "ui"
        ],
        "user": {
            "id": 62319,
            "name": "Anton Aheichanka",
            "username": "madebyanton",
            "html_url": "https://dribbble.com/madebyanton",
            "avatar_url": "https://cdn.dribbble.com/users/62319/avatars/normal/cf4ad999f66633f9ba68e4a52ab111d5.png?1497409787",
            "bio": "Passion for creating clean, thoughtful, attractive design solutions.",
            "location": "Denver, CO",
            "links": {
                "twitter": "https://twitter.com/madebyanton"
            },
            "buckets_count": 11,
            "comments_received_count": 820,
            "followers_count": 11789,
            "followings_count": 496,
            "likes_count": 4206,
            "likes_received_count": 38042,
            "projects_count": 6,
            "rebounds_received_count": 18,
            "shots_count": 39,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/62319/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/62319/followers",
            "following_url": "https://api.dribbble.com/v1/users/62319/following",
            "likes_url": "https://api.dribbble.com/v1/users/62319/likes",
            "projects_url": "https://api.dribbble.com/v1/users/62319/projects",
            "shots_url": "https://api.dribbble.com/v1/users/62319/shots",
            "teams_url": "https://api.dribbble.com/v1/users/62319/teams",
            "created_at": "2011-09-16T22:18:24Z",
            "updated_at": "2017-08-20T11:33:25Z"
        },
        "team": {
            "id": 50942,
            "name": "InVision",
            "username": "InVisionApp",
            "html_url": "https://dribbble.com/InVisionApp",
            "avatar_url": "https://cdn.dribbble.com/users/50942/avatars/normal/bb4685dbe9de3d043ccef3293247a579.png?1493296205",
            "bio": "Design better experiences with InVision, a prototyping, collaboration, and workflow platform.",
            "location": "New York, NY",
            "links": {
                "web": "http://www.InVisionApp.com",
                "twitter": "https://twitter.com/InVisionApp"
            },
            "buckets_count": 0,
            "comments_received_count": 353,
            "followers_count": 31650,
            "followings_count": 1011,
            "likes_count": 270,
            "likes_received_count": 1127,
            "projects_count": 2,
            "rebounds_received_count": 19,
            "shots_count": 200,
            "can_upload_shot": true,
            "type": "Team",
            "pro": false,
            "buckets_url": "https://api.dribbble.com/v1/users/50942/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/50942/followers",
            "following_url": "https://api.dribbble.com/v1/users/50942/following",
            "likes_url": "https://api.dribbble.com/v1/users/50942/likes",
            "projects_url": "https://api.dribbble.com/v1/users/50942/projects",
            "shots_url": "https://api.dribbble.com/v1/users/50942/shots",
            "created_at": "2011-08-05T20:04:14Z",
            "updated_at": "2017-08-20T11:38:46Z",
            "members_count": 25,
            "members_url": "https://api.dribbble.com/v1/teams/50942/members",
            "team_shots_url": "https://api.dribbble.com/v1/teams/50942/shots"
        }
    },
    {
        "id": 3721946,
        "title": "👨🏻\u200d💼🔍",
        "description": "<p>C-c-c-combo breaker 💥</p>\n\n<p>Recently, I was asked by an upcoming HR startup to create the entire visual presence for them. So... here's my first attempt!</p>\n\n<p>I finally had an opportunity to play with some illustrations ✍🏻 Looking forward to hearing your thoughts on this!</p>\n\n<p>If you enjoyed this shot, make sure to take a look at the attachment! 💓</p>\n\n<p>—</p>\n\n<p>Interested in seeing more <strong>*real*</strong> projects like this one? Follow my team at <a href=\"https://dribbble.com/tonikstudio\" rel=\"nofollow noreferrer\">Tonik</a> – we don’t bother with random concepts for the drawer 💁🏼\u200d♂️</p>\n\n<p></p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/600368/screenshots/3721946/shot.png",
            "normal": "https://cdn.dribbble.com/users/600368/screenshots/3721946/shot_1x.png",
            "teaser": "https://cdn.dribbble.com/users/600368/screenshots/3721946/shot_teaser.png"
        },
        "views_count": 13640,
        "likes_count": 1144,
        "comments_count": 39,
        "attachments_count": 1,
        "rebounds_count": 0,
        "buckets_count": 218,
        "created_at": "2017-08-09T07:21:06Z",
        "updated_at": "2017-08-10T15:12:16Z",
        "html_url": "https://dribbble.com/shots/3721946-",
        "attachments_url": "https://api.dribbble.com/v1/shots/3721946/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3721946/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3721946/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3721946/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3721946/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3721946/rebounds",
        "animated": false,
        "tags": [
            "colorful",
            "gradient",
            "header",
            "hero",
            "homepage",
            "illustration",
            "isometric",
            "landing page",
            "orange",
            "purple",
            "shapes"
        ],
        "user": {
            "id": 600368,
            "name": "Michał Roszyk",
            "username": "michalroszyk",
            "html_url": "https://dribbble.com/michalroszyk",
            "avatar_url": "https://cdn.dribbble.com/users/600368/avatars/normal/29d257105a616933ebce911535a166b1.jpg?1488318828",
            "bio": "I design real things and experiences — no concepts or DailyUI sh*t ☄",
            "location": "Poznań, Poland, Europe",
            "links": {},
            "buckets_count": 5,
            "comments_received_count": 222,
            "followers_count": 1427,
            "followings_count": 176,
            "likes_count": 32132,
            "likes_received_count": 6940,
            "projects_count": 0,
            "rebounds_received_count": 4,
            "shots_count": 18,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/600368/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/600368/followers",
            "following_url": "https://api.dribbble.com/v1/users/600368/following",
            "likes_url": "https://api.dribbble.com/v1/users/600368/likes",
            "projects_url": "https://api.dribbble.com/v1/users/600368/projects",
            "shots_url": "https://api.dribbble.com/v1/users/600368/shots",
            "teams_url": "https://api.dribbble.com/v1/users/600368/teams",
            "created_at": "2014-06-21T23:53:39Z",
            "updated_at": "2017-08-20T08:17:25Z"
        },
        "team": {
            "id": 653150,
            "name": "tonik",
            "username": "tonikstudio",
            "html_url": "https://dribbble.com/tonikstudio",
            "avatar_url": "https://cdn.dribbble.com/users/653150/avatars/normal/1a7d1e23c400b4f4bdc8774bff2459fe.png?1430426412",
            "bio": "Conversion–oriented UX/UI. What&#39;s up?",
            "location": "Poznań, Poland",
            "links": {
                "web": "http://www.tonik.pl"
            },
            "buckets_count": 0,
            "comments_received_count": 6,
            "followers_count": 3295,
            "followings_count": 540,
            "likes_count": 653,
            "likes_received_count": 128,
            "projects_count": 8,
            "rebounds_received_count": 23,
            "shots_count": 164,
            "can_upload_shot": true,
            "type": "Team",
            "pro": false,
            "buckets_url": "https://api.dribbble.com/v1/users/653150/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/653150/followers",
            "following_url": "https://api.dribbble.com/v1/users/653150/following",
            "likes_url": "https://api.dribbble.com/v1/users/653150/likes",
            "projects_url": "https://api.dribbble.com/v1/users/653150/projects",
            "shots_url": "https://api.dribbble.com/v1/users/653150/shots",
            "created_at": "2014-09-18T10:05:01Z",
            "updated_at": "2017-08-20T11:03:32Z",
            "members_count": 13,
            "members_url": "https://api.dribbble.com/v1/teams/653150/members",
            "team_shots_url": "https://api.dribbble.com/v1/teams/653150/shots"
        }
    },
    {
        "id": 3719796,
        "title": "Stuff",
        "description": "<p>Promo stuffs. </p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/52758/screenshots/3719796/jay_fletcher_promo_2017_dribbble_small.jpg",
            "normal": "https://cdn.dribbble.com/users/52758/screenshots/3719796/jay_fletcher_promo_2017_dribbble_small_1x.jpg",
            "teaser": "https://cdn.dribbble.com/users/52758/screenshots/3719796/jay_fletcher_promo_2017_dribbble_small_teaser.jpg"
        },
        "views_count": 8239,
        "likes_count": 988,
        "comments_count": 24,
        "attachments_count": 1,
        "rebounds_count": 0,
        "buckets_count": 63,
        "created_at": "2017-08-08T13:03:59Z",
        "updated_at": "2017-08-08T13:25:09Z",
        "html_url": "https://dribbble.com/shots/3719796-Stuff",
        "attachments_url": "https://api.dribbble.com/v1/shots/3719796/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3719796/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3719796/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3719796/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3719796/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3719796/rebounds",
        "animated": false,
        "tags": [
            "bird",
            "cocktail",
            "feather",
            "fire",
            "fish",
            "goat",
            "hen",
            "horse",
            "ocean",
            "pig",
            "shrimp",
            "sun"
        ],
        "user": {
            "id": 52758,
            "name": "Jay Fletcher",
            "username": "jfletcherdesign",
            "html_url": "https://dribbble.com/jfletcherdesign",
            "avatar_url": "https://cdn.dribbble.com/users/52758/avatars/normal/04b487040657c183a70ec1de1532d3e8.jpg?1486579866",
            "bio": "",
            "location": "Charleston, SC",
            "links": {
                "web": "http://www.jfletcherdesign.com",
                "twitter": "https://twitter.com/jfletcherdesign"
            },
            "buckets_count": 0,
            "comments_received_count": 6317,
            "followers_count": 20831,
            "followings_count": 569,
            "likes_count": 7413,
            "likes_received_count": 164381,
            "projects_count": 11,
            "rebounds_received_count": 381,
            "shots_count": 592,
            "teams_count": 0,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/52758/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/52758/followers",
            "following_url": "https://api.dribbble.com/v1/users/52758/following",
            "likes_url": "https://api.dribbble.com/v1/users/52758/likes",
            "projects_url": "https://api.dribbble.com/v1/users/52758/projects",
            "shots_url": "https://api.dribbble.com/v1/users/52758/shots",
            "teams_url": "https://api.dribbble.com/v1/users/52758/teams",
            "created_at": "2011-08-13T23:30:38Z",
            "updated_at": "2017-08-20T14:40:38Z"
        },
        "team": null
    },
    {
        "id": 3737711,
        "title": "Enough",
        "description": "<p>We know who he talks to.</p>\n\n<p>(edit: I updated it, so I just put it <a href=\"https://www.behance.net/gallery/55791121/To-be-clear\" rel=\"nofollow noreferrer\"> here </a> )</p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/35381/screenshots/3737711/trump.png",
            "normal": "https://cdn.dribbble.com/users/35381/screenshots/3737711/trump_1x.png",
            "teaser": "https://cdn.dribbble.com/users/35381/screenshots/3737711/trump_teaser.png"
        },
        "views_count": 9367,
        "likes_count": 950,
        "comments_count": 79,
        "attachments_count": 0,
        "rebounds_count": 1,
        "buckets_count": 14,
        "created_at": "2017-08-15T20:20:33Z",
        "updated_at": "2017-08-15T22:27:57Z",
        "html_url": "https://dribbble.com/shots/3737711-Enough",
        "attachments_url": "https://api.dribbble.com/v1/shots/3737711/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3737711/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3737711/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3737711/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3737711/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3737711/rebounds",
        "animated": false,
        "tags": [
            "charlottesville",
            "trump"
        ],
        "user": {
            "id": 35381,
            "name": "Meg",
            "username": "megdraws",
            "html_url": "https://dribbble.com/megdraws",
            "avatar_url": "https://cdn.dribbble.com/users/35381/avatars/normal/869f8f2bd1c77bb7304312e3e5c6a245.png?1494900138",
            "bio": "",
            "location": "Vancouver",
            "links": {
                "web": "https://medium.com/@megdraws",
                "twitter": "https://twitter.com/MegDraws"
            },
            "buckets_count": 16,
            "comments_received_count": 4791,
            "followers_count": 26009,
            "followings_count": 481,
            "likes_count": 35674,
            "likes_received_count": 141467,
            "projects_count": 0,
            "rebounds_received_count": 125,
            "shots_count": 581,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/35381/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/35381/followers",
            "following_url": "https://api.dribbble.com/v1/users/35381/following",
            "likes_url": "https://api.dribbble.com/v1/users/35381/likes",
            "projects_url": "https://api.dribbble.com/v1/users/35381/projects",
            "shots_url": "https://api.dribbble.com/v1/users/35381/shots",
            "teams_url": "https://api.dribbble.com/v1/users/35381/teams",
            "created_at": "2011-05-16T22:10:42Z",
            "updated_at": "2017-08-20T14:11:01Z"
        },
        "team": null
    },
    {
        "id": 3736866,
        "title": "Boat Mark",
        "description": null,
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/31752/screenshots/3736866/boat_mark.jpg",
            "normal": "https://cdn.dribbble.com/users/31752/screenshots/3736866/boat_mark_1x.jpg",
            "teaser": "https://cdn.dribbble.com/users/31752/screenshots/3736866/boat_mark_teaser.jpg"
        },
        "views_count": 7950,
        "likes_count": 869,
        "comments_count": 22,
        "attachments_count": 0,
        "rebounds_count": 0,
        "buckets_count": 32,
        "created_at": "2017-08-15T14:42:51Z",
        "updated_at": "2017-08-15T16:00:10Z",
        "html_url": "https://dribbble.com/shots/3736866-Boat-Mark",
        "attachments_url": "https://api.dribbble.com/v1/shots/3736866/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3736866/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3736866/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3736866/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3736866/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3736866/rebounds",
        "animated": false,
        "tags": [],
        "user": {
            "id": 31752,
            "name": "Nick Slater",
            "username": "slaterdesign",
            "html_url": "https://dribbble.com/slaterdesign",
            "avatar_url": "https://cdn.dribbble.com/users/31752/avatars/normal/312157471aa9ba31c98655135988e440.png?1441221178",
            "bio": "Designer and Illustrator at Asana.",
            "location": "Palo Alto, Ca",
            "links": {
                "web": "http://www.nicholasslater.co/",
                "twitter": "https://twitter.com/slaterdesign"
            },
            "buckets_count": 0,
            "comments_received_count": 15057,
            "followers_count": 71313,
            "followings_count": 1814,
            "likes_count": 57449,
            "likes_received_count": 380810,
            "projects_count": 0,
            "rebounds_received_count": 444,
            "shots_count": 764,
            "teams_count": 4,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/31752/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/31752/followers",
            "following_url": "https://api.dribbble.com/v1/users/31752/following",
            "likes_url": "https://api.dribbble.com/v1/users/31752/likes",
            "projects_url": "https://api.dribbble.com/v1/users/31752/projects",
            "shots_url": "https://api.dribbble.com/v1/users/31752/shots",
            "teams_url": "https://api.dribbble.com/v1/users/31752/teams",
            "created_at": "2011-04-30T23:12:27Z",
            "updated_at": "2017-08-20T14:21:12Z"
        },
        "team": null
    },
    {
        "id": 3717188,
        "title": "What type of person are you?",
        "description": "<p>👉 <a href=\"http://galshir.com/life-balance/\" rel=\"nofollow noreferrer\">Play with it live</a></p>\n\n<p><a href=\"http://facebook.com/thegalshir\" rel=\"nofollow noreferrer\">Facebook</a> | <a href=\"http://instagram.com/thegalshir\" rel=\"nofollow noreferrer\">Instagram</a> | <a href=\"http://twitter.com/galgalshir\" rel=\"nofollow noreferrer\">Twitter</a> | <a href=\"http://youtube.com/galshir\" rel=\"nofollow noreferrer\">YouTube</a> | <a href=\"http://galshir.com/?ref=dribbble\" rel=\"nofollow noreferrer\">Subscribe</a></p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/729829/screenshots/3717188/galshir-life-balance.gif",
            "normal": "https://cdn.dribbble.com/users/729829/screenshots/3717188/galshir-life-balance_1x.gif",
            "teaser": "https://cdn.dribbble.com/users/729829/screenshots/3717188/galshir-life-balance_teaser.gif"
        },
        "views_count": 11927,
        "likes_count": 883,
        "comments_count": 31,
        "attachments_count": 0,
        "rebounds_count": 0,
        "buckets_count": 52,
        "created_at": "2017-08-07T14:55:35Z",
        "updated_at": "2017-08-14T09:04:44Z",
        "html_url": "https://dribbble.com/shots/3717188-What-type-of-person-are-you",
        "attachments_url": "https://api.dribbble.com/v1/shots/3717188/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3717188/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3717188/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3717188/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3717188/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3717188/rebounds",
        "animated": true,
        "tags": [
            "switch",
            "toggles"
        ],
        "user": {
            "id": 729829,
            "name": "Gal Shir",
            "username": "galshir",
            "html_url": "https://dribbble.com/galshir",
            "avatar_url": "https://cdn.dribbble.com/users/729829/avatars/normal/974031b6ff1e4a51505f6abaf879c00d.jpg?1481887864",
            "bio": "Product designer &amp; art director currently leading the design at Lemonade",
            "location": "Tel Aviv",
            "links": {
                "web": "http://www.galshir.com",
                "twitter": "https://twitter.com/galgalshir"
            },
            "buckets_count": 2,
            "comments_received_count": 1659,
            "followers_count": 14619,
            "followings_count": 1547,
            "likes_count": 4072,
            "likes_received_count": 52787,
            "projects_count": 2,
            "rebounds_received_count": 14,
            "shots_count": 102,
            "teams_count": 0,
            "can_upload_shot": true,
            "type": "Player",
            "pro": false,
            "buckets_url": "https://api.dribbble.com/v1/users/729829/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/729829/followers",
            "following_url": "https://api.dribbble.com/v1/users/729829/following",
            "likes_url": "https://api.dribbble.com/v1/users/729829/likes",
            "projects_url": "https://api.dribbble.com/v1/users/729829/projects",
            "shots_url": "https://api.dribbble.com/v1/users/729829/shots",
            "teams_url": "https://api.dribbble.com/v1/users/729829/teams",
            "created_at": "2015-01-05T10:52:17Z",
            "updated_at": "2017-08-20T14:38:19Z"
        },
        "team": null
    },
    {
        "id": 3725106,
        "title": "Pigeon Pigeoff",
        "description": "<p>Great illustration by <a href=\"https://dribbble.com/19849\">@Julian Burford</a>\n<br />Animation <a href=\"https://dribbble.com/1342032\">@Matthew Jedrzejewski</a></p>\n\n<p>Created using Joysticks 'n Sliders by <a href=\"https://dribbble.com/1106666\">@Mike Overbeck</a>.\n<br />Head, Eyes, Pupils, Beak controlled independently. </p>\n\n<p>Now you can test it by yourself! Check AE files and have fun with this great plugin.</p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/1342032/screenshots/3725106/pigeon-pigeoff.gif",
            "normal": "https://cdn.dribbble.com/users/1342032/screenshots/3725106/pigeon-pigeoff_1x.gif",
            "teaser": "https://cdn.dribbble.com/users/1342032/screenshots/3725106/pigeon-pigeoff_teaser.gif"
        },
        "views_count": 11544,
        "likes_count": 947,
        "comments_count": 58,
        "attachments_count": 1,
        "rebounds_count": 0,
        "buckets_count": 96,
        "created_at": "2017-08-10T08:02:36Z",
        "updated_at": "2017-08-10T17:57:48Z",
        "html_url": "https://dribbble.com/shots/3725106-Pigeon-Pigeoff",
        "attachments_url": "https://api.dribbble.com/v1/shots/3725106/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3725106/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3725106/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3725106/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3725106/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3725106/rebounds",
        "rebound_source_url": "https://api.dribbble.com/v1/shots/416828",
        "animated": true,
        "tags": [
            "2d",
            "after effects",
            "animation",
            "duik",
            "gif",
            "joystick n sliders",
            "loop",
            "motion",
            "motiondesign",
            "pigeon",
            "rig",
            "rigg"
        ],
        "user": {
            "id": 1342032,
            "name": "Matthew Jedrzejewski",
            "username": "MattJedrzejewski",
            "html_url": "https://dribbble.com/MattJedrzejewski",
            "avatar_url": "https://cdn.dribbble.com/users/1342032/avatars/normal/0fdaade3183db84ff500a0a3a4240d72.jpg?1472029133",
            "bio": "Designer, Director &amp; Animator. \nLocated in Warsaw.\nAvailable for hire.\nmatthew.jedrzejewski@gmail.com",
            "location": "Warsaw, Poland",
            "links": {
                "web": "http://www.mattjedrzejewski.com"
            },
            "buckets_count": 2,
            "comments_received_count": 344,
            "followers_count": 1545,
            "followings_count": 579,
            "likes_count": 8081,
            "likes_received_count": 6151,
            "projects_count": 1,
            "rebounds_received_count": 0,
            "shots_count": 36,
            "teams_count": 0,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/1342032/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/1342032/followers",
            "following_url": "https://api.dribbble.com/v1/users/1342032/following",
            "likes_url": "https://api.dribbble.com/v1/users/1342032/likes",
            "projects_url": "https://api.dribbble.com/v1/users/1342032/projects",
            "shots_url": "https://api.dribbble.com/v1/users/1342032/shots",
            "teams_url": "https://api.dribbble.com/v1/users/1342032/teams",
            "created_at": "2016-08-24T08:58:19Z",
            "updated_at": "2017-08-20T11:20:29Z"
        },
        "team": null
    },
    {
        "id": 3717193,
        "title": "OK",
        "description": "<p>Daily practice</p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/756147/screenshots/3717193/okay.gif",
            "normal": "https://cdn.dribbble.com/users/756147/screenshots/3717193/okay_1x.gif",
            "teaser": "https://cdn.dribbble.com/users/756147/screenshots/3717193/okay_teaser.gif"
        },
        "views_count": 13243,
        "likes_count": 853,
        "comments_count": 25,
        "attachments_count": 0,
        "rebounds_count": 0,
        "buckets_count": 45,
        "created_at": "2017-08-07T14:56:57Z",
        "updated_at": "2017-08-07T14:58:35Z",
        "html_url": "https://dribbble.com/shots/3717193-OK",
        "attachments_url": "https://api.dribbble.com/v1/shots/3717193/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3717193/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3717193/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3717193/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3717193/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3717193/rebounds",
        "animated": true,
        "tags": [
            "2d",
            "after effects",
            "animation",
            "behance",
            "cel",
            "flat",
            "framebyframe",
            "liquid",
            "logo animation",
            "motion design",
            "motion graphics",
            "photoshop"
        ],
        "user": {
            "id": 756147,
            "name": "Eduard Mykhailov",
            "username": "eduard_ov",
            "html_url": "https://dribbble.com/eduard_ov",
            "avatar_url": "https://cdn.dribbble.com/users/756147/avatars/normal/7ddad08a680c9ef66762bc7ff6f07f19.png?1502294819",
            "bio": "Motion Designer, love to make some cool stuff",
            "location": "Kiev",
            "links": {},
            "buckets_count": 0,
            "comments_received_count": 474,
            "followers_count": 1812,
            "followings_count": 340,
            "likes_count": 6208,
            "likes_received_count": 9695,
            "projects_count": 3,
            "rebounds_received_count": 2,
            "shots_count": 61,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/756147/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/756147/followers",
            "following_url": "https://api.dribbble.com/v1/users/756147/following",
            "likes_url": "https://api.dribbble.com/v1/users/756147/likes",
            "projects_url": "https://api.dribbble.com/v1/users/756147/projects",
            "shots_url": "https://api.dribbble.com/v1/users/756147/shots",
            "teams_url": "https://api.dribbble.com/v1/users/756147/teams",
            "created_at": "2015-02-07T15:33:03Z",
            "updated_at": "2017-08-20T14:11:49Z"
        },
        "team": {
            "id": 135634,
            "name": "Norde Agency",
            "username": "norde",
            "html_url": "https://dribbble.com/norde",
            "avatar_url": "https://cdn.dribbble.com/users/135634/avatars/normal/2278a1c672a9ed37f91ee6df158ec94e.png?1500409122",
            "bio": "Norde Digital Agency. We&#39;re looking to work with awesome people building their products!  Work inquiries: hello@norde.st",
            "location": "Tel Aviv",
            "links": {
                "twitter": "https://twitter.com/kyrilku"
            },
            "buckets_count": 0,
            "comments_received_count": 898,
            "followers_count": 15048,
            "followings_count": 984,
            "likes_count": 298,
            "likes_received_count": 43350,
            "projects_count": 17,
            "rebounds_received_count": 57,
            "shots_count": 346,
            "can_upload_shot": true,
            "type": "Team",
            "pro": false,
            "buckets_url": "https://api.dribbble.com/v1/users/135634/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/135634/followers",
            "following_url": "https://api.dribbble.com/v1/users/135634/following",
            "likes_url": "https://api.dribbble.com/v1/users/135634/likes",
            "projects_url": "https://api.dribbble.com/v1/users/135634/projects",
            "shots_url": "https://api.dribbble.com/v1/users/135634/shots",
            "created_at": "2012-04-20T22:46:41Z",
            "updated_at": "2017-08-20T14:39:44Z",
            "members_count": 3,
            "members_url": "https://api.dribbble.com/v1/teams/135634/members",
            "team_shots_url": "https://api.dribbble.com/v1/teams/135634/shots"
        }
    },
    {
        "id": 3731362,
        "title": "Event cards iOS interaction",
        "description": "<p>Hope you like it. ❤️</p>\n\n<p>Follow me on <a href=\"https://www.instagram.com/divan_raj/\" rel=\"nofollow noreferrer\">Instagram</a> | <a href=\"https://twitter.com/desdivj\" rel=\"nofollow noreferrer\">Twitter</a> | <a href=\"https://www.behance.net/divangraphicdesigner\" rel=\"nofollow noreferrer\">Behance</a></p>\n\n<p>Checkout more inspiration <a href=\"https://www.behance.net/gallery/55581473/UI-Interaction-Gallery\" rel=\"nofollow noreferrer\">here</a></p>\n\n<p></p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/692322/screenshots/3731362/dribbble.gif",
            "normal": "https://cdn.dribbble.com/users/692322/screenshots/3731362/dribbble_1x.gif",
            "teaser": "https://cdn.dribbble.com/users/692322/screenshots/3731362/dribbble_teaser.gif"
        },
        "views_count": 12664,
        "likes_count": 924,
        "comments_count": 30,
        "attachments_count": 2,
        "rebounds_count": 0,
        "buckets_count": 151,
        "created_at": "2017-08-13T06:38:26Z",
        "updated_at": "2017-08-14T07:29:01Z",
        "html_url": "https://dribbble.com/shots/3731362-Event-cards-iOS-interaction",
        "attachments_url": "https://api.dribbble.com/v1/shots/3731362/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3731362/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3731362/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3731362/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3731362/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3731362/rebounds",
        "rebound_source_url": "https://api.dribbble.com/v1/shots/3721883",
        "animated": true,
        "tags": [
            "animation",
            "cards",
            "design",
            "events",
            "interaction",
            "ios app",
            "landing page",
            "mobile",
            "presentation",
            "swipe",
            "uiux",
            "webdesign"
        ],
        "user": {
            "id": 692322,
            "name": "Divan Raj ",
            "username": "divanraj",
            "html_url": "https://dribbble.com/divanraj",
            "avatar_url": "https://cdn.dribbble.com/users/692322/avatars/normal/64cb1e3181907a25d69d09f1733f9679.jpg?1499508866",
            "bio": "Freelancer ( iOS / Android / Web / Animation )  |\nFor Project Enquiries  -  desdivj@gmail.com  |\nSkype : divanraj1601\n\n",
            "location": "Bangalore, India",
            "links": {
                "web": "http://www.divanraj.com",
                "twitter": "https://twitter.com/desdivj"
            },
            "buckets_count": 15,
            "comments_received_count": 2881,
            "followers_count": 10339,
            "followings_count": 930,
            "likes_count": 52902,
            "likes_received_count": 65587,
            "projects_count": 17,
            "rebounds_received_count": 84,
            "shots_count": 134,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/692322/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/692322/followers",
            "following_url": "https://api.dribbble.com/v1/users/692322/following",
            "likes_url": "https://api.dribbble.com/v1/users/692322/likes",
            "projects_url": "https://api.dribbble.com/v1/users/692322/projects",
            "shots_url": "https://api.dribbble.com/v1/users/692322/shots",
            "teams_url": "https://api.dribbble.com/v1/users/692322/teams",
            "created_at": "2014-11-13T03:14:44Z",
            "updated_at": "2017-08-20T14:00:29Z"
        },
        "team": null
    },
    {
        "id": 3716026,
        "title": "terhie - find teachers near you",
        "description": "<p>Well met 👋</p>\n\n<p>Terhi is an app made for finding various teachers near your location. Here is small teaser of our visual design exploration.</p>\n\n<p>Enjoy ☄️</p>\n\n<p>--\n<br />Thanks for watching! Let’s connect:\n<br /><a rel=\"nofollow noreferrer\">10clouds.com</a> | <a rel=\"nofollow noreferrer\">Facebook</a> | <a rel=\"nofollow noreferrer\">Twitter</a> | <a rel=\"nofollow noreferrer\">Instagram</a> | <a rel=\"nofollow noreferrer\">Behance</a>\n<br /><strong>We’re available for new projects! Tell us more at <a href=\"mailto:hello@10clouds.com\" rel=\"noreferrer\">hello@10clouds.com</a>.</strong>\n<br />Would you like to join our design team? Send your portfolio at <a href=\"mailto:careers@10clouds.com\" rel=\"noreferrer\">careers@10clouds.com</a>.</p>",
        "width": 400,
        "height": 300,
        "images": {
            "hidpi": "https://cdn.dribbble.com/users/29503/screenshots/3716026/artboard.png",
            "normal": "https://cdn.dribbble.com/users/29503/screenshots/3716026/artboard_1x.png",
            "teaser": "https://cdn.dribbble.com/users/29503/screenshots/3716026/artboard_teaser.png"
        },
        "views_count": 11386,
        "likes_count": 903,
        "comments_count": 12,
        "attachments_count": 2,
        "rebounds_count": 0,
        "buckets_count": 184,
        "created_at": "2017-08-07T07:10:11Z",
        "updated_at": "2017-08-08T09:07:59Z",
        "html_url": "https://dribbble.com/shots/3716026-terhie-find-teachers-near-you",
        "attachments_url": "https://api.dribbble.com/v1/shots/3716026/attachments",
        "buckets_url": "https://api.dribbble.com/v1/shots/3716026/buckets",
        "comments_url": "https://api.dribbble.com/v1/shots/3716026/comments",
        "likes_url": "https://api.dribbble.com/v1/shots/3716026/likes",
        "projects_url": "https://api.dribbble.com/v1/shots/3716026/projects",
        "rebounds_url": "https://api.dribbble.com/v1/shots/3716026/rebounds",
        "animated": false,
        "tags": [
            "app",
            "cards",
            "dark",
            "education",
            "flat",
            "map",
            "ui",
            "ux"
        ],
        "user": {
            "id": 29503,
            "name": "Wojciech Zieliński",
            "username": "acreno",
            "html_url": "https://dribbble.com/acreno",
            "avatar_url": "https://cdn.dribbble.com/users/29503/avatars/normal/531dfec7bf9a0bcf76e7b3d5f13eaae8.jpg?1501157377",
            "bio": "Scout 👎",
            "location": "Warsaw, Poland",
            "links": {
                "twitter": "https://twitter.com/acreno_"
            },
            "buckets_count": 12,
            "comments_received_count": 736,
            "followers_count": 5703,
            "followings_count": 400,
            "likes_count": 5078,
            "likes_received_count": 21975,
            "projects_count": 5,
            "rebounds_received_count": 6,
            "shots_count": 71,
            "teams_count": 1,
            "can_upload_shot": true,
            "type": "Player",
            "pro": true,
            "buckets_url": "https://api.dribbble.com/v1/users/29503/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/29503/followers",
            "following_url": "https://api.dribbble.com/v1/users/29503/following",
            "likes_url": "https://api.dribbble.com/v1/users/29503/likes",
            "projects_url": "https://api.dribbble.com/v1/users/29503/projects",
            "shots_url": "https://api.dribbble.com/v1/users/29503/shots",
            "teams_url": "https://api.dribbble.com/v1/users/29503/teams",
            "created_at": "2011-04-20T15:39:20Z",
            "updated_at": "2017-08-19T17:10:54Z"
        },
        "team": {
            "id": 845019,
            "name": "10Clouds",
            "username": "10Clouds",
            "html_url": "https://dribbble.com/10Clouds",
            "avatar_url": "https://cdn.dribbble.com/users/845019/avatars/normal/93475f3bf87361ad5f76d6cf9fd7d462.png?1476194878",
            "bio": "We are one of the top design &amp; software agencies based in Poland. \nContact us at hello@10clouds.com",
            "location": "Warsaw, Poland, Europe",
            "links": {
                "web": "http://www.10clouds.com",
                "twitter": "https://twitter.com/10clouds"
            },
            "buckets_count": 0,
            "comments_received_count": 15,
            "followers_count": 1648,
            "followings_count": 73,
            "likes_count": 772,
            "likes_received_count": 511,
            "projects_count": 2,
            "rebounds_received_count": 0,
            "shots_count": 65,
            "can_upload_shot": true,
            "type": "Team",
            "pro": false,
            "buckets_url": "https://api.dribbble.com/v1/users/845019/buckets",
            "followers_url": "https://api.dribbble.com/v1/users/845019/followers",
            "following_url": "https://api.dribbble.com/v1/users/845019/following",
            "likes_url": "https://api.dribbble.com/v1/users/845019/likes",
            "projects_url": "https://api.dribbble.com/v1/users/845019/projects",
            "shots_url": "https://api.dribbble.com/v1/users/845019/shots",
            "created_at": "2015-05-12T10:47:03Z",
            "updated_at": "2017-08-20T04:24:37Z",
            "members_count": 8,
            "members_url": "https://api.dribbble.com/v1/teams/845019/members",
            "team_shots_url": "https://api.dribbble.com/v1/teams/845019/shots"
        }
    }
];